# version: '3.8'

services:
  # Service pour la base de données MySQL
  db:
    image: mysql:8.0
    container_name: mysql_db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - db_data:/var/lib/mysql
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "myuser", "-pmypassword"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  php:
    build:
      context: .
      dockerfile: Dockerfile.php
    container_name: php_fpm
    volumes:
      - ./html:/usr/share/nginx/html
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  # Service pour le serveur web Nginx
  web:
    image: nginx:latest
    container_name: nginx_web
    ports:
      - "8080:80"
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - php
      - db
    networks:
      - app-network

  # Service pour phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql_db
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - app-network

# Volumes pour persister les données de la base de données
volumes:
  db_data:

# Réseau pour permettre la communication entre les conteneurs
networks:
  app-network: